apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentName }}
    spec:
      containers:
      - name: {{ .Values.imgeName }}
        image: "{{ .Values.imageRepository}}/{{ .Values.imgeName}}:{{ .Values.imageTag}}"
        ports:
        - containerPort: 80
