apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: appgetway
  name: appgetway-deployment
  namespace: appgetway
spec:
  replicas: 10
  selector: 
    matchLabels:
      app: appgetway
  template: 
    metadata:
      labels: 
        app: appgetway
    spec: 
      containers:
      - name: netflix-container
        image: devopsinsiders/netflix-clone
        ports:
        - containerPort: 80
