  apiVersion: apps/v1
  kind: Deployment
  metadata: 
    name: deployment-pod
    namespace: ganesh-ns

  spec:
    replicas: 20
    selector:
      matchLabels:
        name: ganesh
    template:
      metadata:
        labels:
          name: ganesh
        name: nginx-pod
        namespace: ganesh-ns
      spec:
        containers:
        - name: nginx-container
          image: nginx:perl
          ports:
          - containerPort: 80
        

        
        
