apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - "ollama run llama3.2:1b"
      
