name: Todo-UI-ImageBuilding
pool: Lenovo-laptop
trigger: none
stages:
- stage: 
  jobs:
  - job: 
    displayName: Todu-UI-Image
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'ConnectionToACR'
        repository: 'ui'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
- stage:
  displayName: Deployment of Todo UI 
  jobs:
  - job: 
    displayName: Deployment of Todo UI 
    steps:
    - task: KubernetesManifest@1
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'TodoAKS'
        manifests: 'Maniests/*.yaml'
        containers: 'todoappcontainer.azurecr.io/ui:$(Build.BuildId)'